kind: pipeline
type: docker
name: Docker_only


steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk
    environment:
      DATABASE_STRING:
        from_secret: pgconn
    commands:
      - dotnet build
      - dotnet ef database update --connection $DATABASE_STRING
      
  - name: test
    image: mcr.microsoft.com/dotnet/sdk
    commands:
      - dotnet test
      - dotnet ef database update --connection $DATABASE_STRING
      